### ISSUE TITLE
Port to V?

### ISSUE THREAD

**Issue by ylluminate** [ProtonMail/gluon#304]
For further decoupling from big tech backed infrastructure/langs, it could be both powerful and interesting to port to V (https://github.com/vlang/v) since it's so close to Go syntactically and such an effort could help contribute toward the ongoing push towards 1.0 of the language. It could certainly make the library more performant.

**Comment by jameshoulahan** [comment]
Hey there, thanks for the interest in the project :)

At this stage, this is something we are not interested in doing. We have limited dev time available and need to use it for what makes most sense for our customers. For now, this is Go, as the rest of the codebase we integrate Gluon into is written in Go.
