### ISSUE TITLE
Not respecting rfc3501 (imap4rev1) for ABNF syntaxe

### ISSUE THREAD

**Issue by PhilipRotz** [ProtonMail/gluon#375]
Hi ! And first of all, thank you for your work :rocket: 

I'm using gluon server with a client that only follows IMAP4rev1 RFC, and I got an error while parsing a gluon IMAP response, as it does not follow the ABNF syntaxe everywhere

Here is the steps to reproduce : 

```bash
>> telnet 127.0.0.1 1143
a0 login user1@example.com pass
...
a5 UID SEARCH ALL
* SEARCH 6 7
a5 OK command completed in 337.51µs
``` 

As you can see, the server took "337.51µs" to respond... "µs" -> here is the problem, "µ" is not an ASCII char.
As defined in rfc3501 (IMAP4rev1 that Gluon tends to follow), IMAP syntaxe should follow ABNF.
Quote from rfc3501:
> resp-cond-state = ("OK" / "NO" / "BAD") SP resp-text
> resp-text       = ["[" resp-text-code "]" SP] text
> text            = 1*TEXT-CHAR
> TEXT-CHAR       = any CHAR except CR and LF

and the ABNF rfc5234 tells that CHAR are only US-ASCII

> CHAR           =  %x01-7F
>                                ; any 7-bit US-ASCII character,
>                                ;  excluding NUL

"µ" char is not in this range (as it is UTF-8)

The problem is located here : 
https://github.com/ProtonMail/gluon/blob/aa59753894ec6b039c16d7db193abc2866177b7f/internal/session/context.go#L22-L28

I think this should be fixed to follow rfc3501 

Thank you !!

**Comment by LBeernaertProton** [comment]
Hey @PhilipRotz, thanks for the report. That's indeed an oversight on our part. We'll fix this as soon as we have time.
