### ISSUE TITLE
32 bit support

### ISSUE THREAD

**Issue by benthetechguy** [ProtonMail/gluon#382]
The file limits/imap.go uses `MaxUint32` which is too big for the `int` type on 32 bits and causes builds on those architectures to fail. This seems to be a known issue based on proton-bridge's BUILDS.md file, but I don't see any effort made to solve it. Is this specific number required, or can something else 32-bit-friendly be used?

**Comment by LBeernaertProton** [comment]
For bridge related questions/issues please open an issue in the [Proton Bridge Issue Tracker](https://github.com/ProtonMail/proton-bridge/issues).

Regarding Gluon side, 32bit support is not a priority for us. I'm happy to provide assistance if you wish to address these issues in a pull request.

For this particular case, it would suffice to change the data type to a 32bit unsigned integer if that is currently not the case.
